#!/bin/bash
filename="$0"
image="elespejo/sskcp-x86"
version="test"
container="sskcp-redir"
cmd="supervisord -c /service.conf.d/sskcp-redir.conf"
conf_vol=`pwd`/clientconf
log_vol=`pwd`/clientlog
ports="1080|8388"

Usage(){
    echo "Usage: $filename <command>"
    echo "command options:"
    echo "  start   start $container service"
    echo "  stop    stop $container service"
    echo "  status  display the status of $container service"
}

START(){
    docker run -itd -p 1080:1080 -v ${conf_vol}:/clientconf -v ${log_vol}:/clientlog --name=${container} ${image}:${version} ${cmd}
}

STOP(){
    docker rm -f ${container}
}

STATUS(){
    docker ps -a|grep ${container}
    docker logs ${container}
    sudo netstat -tunpl | egrep ${ports} 

}

if [ "$#" -ne 1 ]; then
    Usage
else
    case "$1" in
        start)
            START
            ;;
        stop)
            STOP
            ;;
        status)
            STATUS
            ;;       
        *)
            Usage
            ;;
    esac
fi
