#!/bin/bash
filename="$0"
image="meninasx86/sskcp-x86"
version="test"
container="sskcp-server"
cmd="supervisord -c /service.conf.d/sskcp-server.conf"
conf_vol=`pwd`/serverconf
log_vol=`pwd`/serverlog
ports="8388|4000"

Usage(){
    echo "Usage: $filename <command>"
    echo "command options:"
    echo "  start   start $container service"
    echo "  stop    stop $container service"
    echo "  status  display the status of $container service"
}

START(){
    docker run -itd -v ${conf_vol}:/serverconf -v ${log_vol}:/serverlog --name=${container} ${image}:${version} ${cmd}
}

STOP(){
    docker rm -f ${container}
}

STATUS(){
    docker ps -a|grep ${container}
    docker logs ${container}
    sudo netstat -tunpl | egrep ${ports} 
}

if [ "$#" -ne 1 ]; then
    Usage
else
    case "$1" in
        start)
            START
            ;;
        stop)
            STOP
            ;;
        status)
            STATUS
            ;;       
        *)
            Usage
            ;;
    esac
fi
