version: '3.2'
services: 
  sskcp-server:
    image: ${ORG}/${REPO}-${ARCH}:${VERSION}

    restart: always
    network_mode: "host"

    volumes: 
      - type: bind
        source: ${CONF_DIR}
        target: /serverconf
      - type: bind
        source: ${LOG_DIR}
        target: /serverlog
    command: supervisord -c /service.conf.d/sskcp-server-${ARCH}.conf
