language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: mpqQG1HsXfVtYOZBujiOjQy0VTXz9s+t+QhXbvhE3HBLDX9yODwIwq0LOONT7T7z+w/q3rGZF/2eB5eSZmhMpXQvD5WoaOoa70VFLgP/wfobSHA9l87H0LYY4qHXP4KoowNkG6bnxXkCC5Yh4snYNbQdJrWGi+Zj8btZFzgYRBMrJ+2Hl9AuWOFnUs0rIqHjiQhXDO0Ain5V0kkEy19upztRaM/7biiJ2UKPgrnp4l+ft73rxCy6G/h3wNfm+y+JA+TgggbXOVyOijpouqt8awL8v9UI5ExDTPEyjILcTRrzcapQttLxEipfOBDjJkDG/CeZ5V97P/K8Boh+DVPkq2npdCKBMj/DENVH3xkQ0hVy15sV2oJclLLNmaJC2+rtIK9V6LU4LM3H8Txm4cZGnXEAs+Z7cNY2KwsRZgCgN+cNPxRHMEPEi+ZAwDYg7tUQCmkReu1qLmOgEH/iaiCMi56Yb1cK3XC9qDD/EKC4Jepb9bSSwemtOgzz/+d90YsSusvtvQ+xp/sb+biCLdSzUDjqW8aRwZjUfNjRQauIs1o8okbxnKx9ojFE2cFbvPoMCDDzpkVn8jBEc/m+m0gXMgPdTwY8PwX7+DYoVWGiuS3p2czLo21p9GPsHZLwufA3RY7LE+nhLqOvOZyionz8AMZcSxa01G7M+3I88EMTlVY=
  - secure: lp9diI6PX/VNWcE80zJm/GJreAQM7WcL6gA6j/dt07sZqlpZRbqrVCKzYZSBnww/Gl2y1iIWH//sV+AQYX8E58dCrx05NXrcPwpNjBaBgtmT6BsRbDJ6AdUGs0y36y1aYcb11d1vRVoWUjpaZaO6aLSqV3kwldNH5/9e3IYPr95XfvNLT8JiCsrFrUTvkctwrTAQwHWp3VyGQS75CFZ3tSaDBIpmzSqNDrdQHDfhzLh6WW/2dF35nuH1cqSRCe2a9gPJ9xQalg5oDQzUTmsWaUFUk24G35LzZYUlGPyfs8kf3C6Ena8oWbzAvT/vpPeJm/qg5b9gNz/RYGCzE5j1s6I65DRThNauj554I7FyD7nuD56LBGN6ftHhJzkaiZ/lru0A7WyBm3P0JX86Wcqmdvu4DKZVTyPY/xMG1SnvEUJ2Eq4EpK69KtblCEKiOKn2/yMtZgZmFhYbndyZRMhmYyooPPkHSjWwvUDShXsjhhzWzFlXAr0x11Jn1Os/spiUuVNqTZk13jaKcpll4PDRiG+uD5z6dYQX8M3K8h9byI4rwtBwEuDS70KQVkLabAfataW5VcpcNTiz+5qfK4Qf5xM8LN2mFhnz7T3lO5qI5aiRAKC1+lt54ug7C6gOPrfJz/xzeOXAR6klc9sTZivJlnuBVuXTCr7795VY7Q8cxUA=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
deploy:
  - provider: releases
    prerelease: true
    skip_cleanup: true
    api_key:
      secure: oEIJ63+PjEDXQI8Z6FT38X34stqbXbmu4YMe1p9H7XGdIjdl1p5B866dCgx/ctA4FRNobWuJQ58C+JoehbYItO+wsnjOc2mHORuxeaDjhQ4UAW1cU+dAQWe1noEw1rBbVUJwpR0lZGaQlVx8f2v8SQk0kvXAuxBncpJ1SUHEOlVnnd4/rFo+Du6UBQSCYGWwbbDPGhpnEvQs5TSqS27SDNfOcb2HkKo8oRLue3PK/fS0pBWksUIYAmHjAaLhrY2IBTBLOrgwJPXxXVKIOQpTb4pz8tv8jkPK8Y/uXsL8mMsWZNy0GL8T35MI4jU3noPePQsMxmYRuSDeOIvzyPAKpntNvfbaCf7XOTtEMihqvkRlYt4WmawgHJxGWAzJo+6uGFLhq3E4Ic0Op2ATBjUf5ttb8iMNk1ShXKhQId2rzjnG6JSqjvdYnOnO4teXyH4xJDAFGQ+0e7oIsZbw285pnnNRrGo0T8IVzHOnWMrzq8iGFY8XaVnK/V9sFNQ3EdRsV9RU8gSW19vdWSRTm7fsxFLwLXrWDcrKWk+NhMQoKE1lrtWy8rWUug3Re0lAX/MyrQyxUIZQN3lc97GEpqdb4N2ohjZYquPYxmnH2N0WY0o6TQD/HiqTVht71jGYjQEd4rptffcZOW/9IhUg2b9iWcHZXSeAUeao2H6Toxlcvz0=
    file_glob: true
    file: "./*.zip"
    on:
      tags: true
      repo: elespejo/sskcp
  - provider: script
    script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
  - provider: script
    script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
