language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: mpqQG1HsXfVtYOZBujiOjQy0VTXz9s+t+QhXbvhE3HBLDX9yODwIwq0LOONT7T7z+w/q3rGZF/2eB5eSZmhMpXQvD5WoaOoa70VFLgP/wfobSHA9l87H0LYY4qHXP4KoowNkG6bnxXkCC5Yh4snYNbQdJrWGi+Zj8btZFzgYRBMrJ+2Hl9AuWOFnUs0rIqHjiQhXDO0Ain5V0kkEy19upztRaM/7biiJ2UKPgrnp4l+ft73rxCy6G/h3wNfm+y+JA+TgggbXOVyOijpouqt8awL8v9UI5ExDTPEyjILcTRrzcapQttLxEipfOBDjJkDG/CeZ5V97P/K8Boh+DVPkq2npdCKBMj/DENVH3xkQ0hVy15sV2oJclLLNmaJC2+rtIK9V6LU4LM3H8Txm4cZGnXEAs+Z7cNY2KwsRZgCgN+cNPxRHMEPEi+ZAwDYg7tUQCmkReu1qLmOgEH/iaiCMi56Yb1cK3XC9qDD/EKC4Jepb9bSSwemtOgzz/+d90YsSusvtvQ+xp/sb+biCLdSzUDjqW8aRwZjUfNjRQauIs1o8okbxnKx9ojFE2cFbvPoMCDDzpkVn8jBEc/m+m0gXMgPdTwY8PwX7+DYoVWGiuS3p2czLo21p9GPsHZLwufA3RY7LE+nhLqOvOZyionz8AMZcSxa01G7M+3I88EMTlVY=
  - secure: lp9diI6PX/VNWcE80zJm/GJreAQM7WcL6gA6j/dt07sZqlpZRbqrVCKzYZSBnww/Gl2y1iIWH//sV+AQYX8E58dCrx05NXrcPwpNjBaBgtmT6BsRbDJ6AdUGs0y36y1aYcb11d1vRVoWUjpaZaO6aLSqV3kwldNH5/9e3IYPr95XfvNLT8JiCsrFrUTvkctwrTAQwHWp3VyGQS75CFZ3tSaDBIpmzSqNDrdQHDfhzLh6WW/2dF35nuH1cqSRCe2a9gPJ9xQalg5oDQzUTmsWaUFUk24G35LzZYUlGPyfs8kf3C6Ena8oWbzAvT/vpPeJm/qg5b9gNz/RYGCzE5j1s6I65DRThNauj554I7FyD7nuD56LBGN6ftHhJzkaiZ/lru0A7WyBm3P0JX86Wcqmdvu4DKZVTyPY/xMG1SnvEUJ2Eq4EpK69KtblCEKiOKn2/yMtZgZmFhYbndyZRMhmYyooPPkHSjWwvUDShXsjhhzWzFlXAr0x11Jn1Os/spiUuVNqTZk13jaKcpll4PDRiG+uD5z6dYQX8M3K8h9byI4rwtBwEuDS70KQVkLabAfataW5VcpcNTiz+5qfK4Qf5xM8LN2mFhnz7T3lO5qI5aiRAKC1+lt54ug7C6gOPrfJz/xzeOXAR6klc9sTZivJlnuBVuXTCr7795VY7Q8cxUA=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
deploy:
  - provider: releases
    prerelease: true
    skip_cleanup: true
    api_key:
      secure: n196QGpADQpnme7yiKYm/l1J8IXEOxVSP6HSPhf685g7vTVPiqK85wSEUwYFT85Elb7xJH0euc98aXbldZ188+yzAs55iAcbznCIeY+49JfsQVbM23E/yi3nXuJgfJNTfGXwZ4xNYvEnM93H7HUP8wR/VrrvOFlciaL5oMBtVejRqXddHnUFESaYKPCmy9xIW9aFfxjKKYp1xlhYvsOhcvqeVdrndGCoME1+QGgWa71lhYZvlYJUuUQyxg8gCnpCyInSyA13injRRr7m3+DmccTwbAlCXHjZsUwczBcbljc/XT4crUKiyRmomrtHoZEBXWJ9/YPvQKGhUj09vE+Q4/poFyC8CyZviRW/DBgWMsAbENGwgB/K8k2J5jX+fn97Nbd6+m0pEajLTewiwPFvuL1ItCq+Nyxjd7A4NaIg3JKSNUoGg8K3BHfTYP3AeZ+CpfBmhoV//Nt1tLzGReHbv9SZfV/RcIIfLdD5nkiwh4JFl0ANLRsoBRcE/VRqmQf5eQiM8ysDd3gpTNF0PT7CbQoYkfW8JnDQ+1FCW4qpeNEtCHMpMeyxh0lSfZgMDJCy0NN5esi4tzgdisuYRR+Gz3PgGSV9ctJJ2NVvy9bw1hAddJuEBRoXNvZU51GSjYI7VCnceaMtrZ8LTdaT3o2Y+QojiYz5HMc3CpzRM3mrW6c=
    file_glob: true
    file: "./*.zip"
    on:
      tags: true
      repo: elespejo/sskcp
  - provider: script
    script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
  - provider: script
    script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
