language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: p45M3or+Mo8A2yCtiUpkLInyigO0UE4R26Mpx9bEd2RDIillhFlHeK4EFsGjT7GI4QFz2nrfPvyQfmHlw3Tb5ZxtIC5nb2qonoh4mUF9A2LgWCXYISYttW6msuMREU5iTBzdDY1Ki6cRGUuO505Vp3oGrQQ5OwmwYg8vdS8fSajpXjQLJdZOlXdnSeSvbRB6PakXe7G5FcKy4imwp/f1gU3IejwbLv8TJT8ogk68qeyf6fUhL1yPYeddX+giqrOUzqVBZphDjaEvrGWBIZ+xau2zwBap5PYCU3v2Z50MCw7uTP3g3ST0STXHGGPvfm7PJv6wBKMhrroakV8uykxW4Q4DalCvRMhTX+EYHxpyOtZ2RuvzbkskRBX09XQlvcq9VfJI8OoqzXs//VCxouhEpFk1kP/70O+eBUDXKRmI7GoYw+1dbO3zzn9bEwD0711iCp9cU31fJz846eE5mo6IQtcq+m1x2ZJkl1GiPinjKSjnZUR42WMve/kAGFQzvmOpy5uf4E56Yn7EoQq2DT521FWNO48X7XBLsUM3b2+CqPGBJu4bef1kAwTMiDp3dUAN/DuWMB9mC9ZZ0dLOqLTRO/4NXMRNvCNQUQkwHBi0Ti7AHXokdpnNVbMc4ur1cxG0DI0xV2QFSD3wKfhrk+vOS6/HpRPE0RdyaqlO8PzDYwU=
  - secure: XUc4GItVlBmAuAmch1doDgWqFZi3PNr17kI9oVdHLmGaMisb+f6sOtbQ43RFpV+Ul2dow5NtVM73jMLF0SbHVQsT58a8GltHZSr8Ll67y/vKRTFlqhKbcTay+TjrC2urs0QYu0UE8JAF+kegdXeVMc5460Z6jWDMaiuh2TD8I01lntfnQGSQh1DY1dqBOQ6DVjiAdWAfhDEoUZFqR8GDsMUUjk3S4u5rjeSDwCgtPJOBktVl7rS7VBZilzyulj+7/uAiSJfUaDCCLFR/xNTY7PHu4NtHswaNTJKVBvFoheG4qaywE8Nl8Wi1Oa3H5fjSGMfdDTo8KyUua1XsgTV/JPImDy+Eb/Ddw1JMoyc9GpnCaI+jUl+jE4uc+QiCvqLLMhQiU0+h33A90QM+WZMplFsCmTLq8tkrqZQNT5krifP26ifu+zCwhMNZ+JL4ADcb3eMeR2SnhW4SsAFPYs2N79mVO9qtlJqUu1+i4wO2aNowlDb8XKQvbK1gR4ouoM2+dqu4tYkpjUDmNxgD31s6EJzSo4iSVZ6iR+cAvN81nIxJg3juvFX8qODlAov3dFKKfQxvCPb8oM6x7usnVK2XVCH1zPUY9wc+CfVX7hyBqZCAo/GUY9Il6VFtT8kvb+/CvBxsrNSavp+qKkZM6qbN22+hR+p4mhT2Z/na3gosLZ4=
  - secure: phvFnid0J16b8U8U3Se8XWIOPBHapOz40glwnJy7/1fbUrIbmQo+paqLAvWUy9VgDfv0MOYNfSo4mO0tW/kGz9BCQZ30mN3wYrZUNIXv7j8BXg8jdtXynt5xKEEGaGXpDyOSPNLEwJ9WkAA3PuAh0clsgvie5g9ySOprf99g4W9OfD3k6y4GbEWHHwwg3TsdLm8iUEQbaySphvH5uSeykK1jBHFXd08I6xEoCDhNrfhzgFwKVafcq6J6cU3y7LrjtgBnMNJRyok7fNlFFbd8sjRqBq8IUOeyyYaxVatH7YvtWMyFMoqUvE+axb13NOO3uI4Ill4GQsG7A5PjIVMPdoeil+S8aRuz6MoxjYmy4rd/MalEKvqoRAzTWl/pj28qjaQhXFZNOGYzqk4qr2xPkLmWFziBcBjWpFPTrfOmR/wNdCEjOIpPRMG6vfexZ0l4kok10zMaMQPUxCgQTm6kj5URPcyqt6neKd2O3xfuCjaql8PgU1zEpMwWdKyf8nyvQStgPC7CC5AKZOqc6czy/m2NZExXofJbThdzKKlbrlADEAlGOSeg7xSboZOm0cAqEbOxRXUgcHqlPPg+x/SmNYvb5znIhdBcOd4zJptYIokMC5I2LkKHVII33SONXhSKg8YWtiwzXfaD+CZxxInpShfYfsM+H04MSFQrt8+IJFs=
  - secure: HtTTcz4ZhI5EtSUQX4svpdQRKnOqDZnsiPx33z+W1dyDsL5tjtMYNORwd5TbgIcaj1EsJTWKZcdBSj0IL9YDZbrA1urQg0loZxNRXRymag+iaksILoLao+S2avjdHMt8/jr3YXv+XNMIsIMD2Ks7CdlZkycnlgGPxB5z/ULYGy+xDgGo/vwMkUA05zqr+Iz72HM1iv5N/HCbeIuEXtDU8SUhnLRbZl9F0V+UGx3ApBXoad2Tk53caUzZuG/e9iQkuXUP5c/iItxryIDCfd4Ez4e9RmLbEeVx+Ak+YD4xOLOpweszzNzC779gTLWrv4t125i/eIvXauByfEdXOb4j55Dt9w4av2pTeXRf1IPSOfFvQqSeoSxqEPRnvfBLlBE9ar1fjBWNdp6zaxht6afrGVV/ZMAqSRsuFlQ3pfBkf4mbZQ8KrBRBJVEW5mp1TBB8bbVuqrNQp81k1toCak0uLFSpqpl5l2AIP68vh4+rlUgbkjRkvM4qO1GbGukV5+qIeYNyCl6hZkw4/qUe9XlmoNCk1r33eeQausBa3pCz/aqZLSgWPEDRN9iNltEIgMlPSQY00FEriAAdiSvt1KwVQdLrI8WDPQJuT1K5cv0yLpFgu7UfCG364LXVaIWcCBCdkS3OmCLeUTV3y88VASV6/9Lq2Zql9iZgzXXQ9kUDe8U=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
deploy:
- provider: script
  script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
- provider: script
  script: make pushtohub DOCKER_USER=$DOCKER_USER DOCKER_PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
- provider: releases
  user: $GITHUB_USER
  password: $GITHUB_PASS
  prelease: true
  skip_cleanup: true
  file_glob: true
  file: ./*.zip
  on:
    tags: true
    all_branches: true
