name: CI for sskcp 
on:
  push:
    branches:
      - master
      - develop
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  release_image:
    strategy:
      matrix:
        arch: [armv6, x86]
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: create image
        run: |
          make mk-image ARCH=${{ matrix.arch }}  
        shell: bash
      - name: upload image to docker hub
        run: make pushtohub DOCKER_USER=${{ secrets.DOCKER_USER }} DOCKER_PASS=${{ secrets.DOCKER_PASS}} ARCH=${{ matrix.arch }} TAG=${{ github.ref_name }}
        shell: bash
  release_zip:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: create zip 
        run: make mk-deployment VERSION=${{ github.ref_name }}
        shell: bash
      - name: release a new version
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *.zip
