FROM alpine:3.8

# build shadowsocks-libev
ENV SS_VER 3.2.0 
ENV SS_URL https://github.com/shadowsocks/shadowsocks-libev/releases/download/v$SS_VER/shadowsocks-libev-$SS_VER.tar.gz 


RUN set -ex \
 # Build environment setup
 && apk add --no-cache --virtual .build-deps \
      autoconf \
      automake \
      build-base \
      c-ares-dev \
      libev-dev \
      libtool \
      libsodium-dev \
      linux-headers \
      mbedtls-dev \
      pcre-dev \
      curl \
 # Build & install
 && mkdir /tmp/repo \
 && cd /tmp/repo \
 && curl -sSL $SS_URL | tar xz --strip 1 \
 && autoreconf --install --force \
 && ./configure --prefix=/usr --disable-documentation \
 && make install \
 && apk del .build-deps \
 # Runtime dependencies setup
 && apk add --no-cache \
      rng-tools \
      $(scanelf --needed --nobanner /usr/bin/ss-* \
      | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
      | sort -u) \
 && rm -rf /tmp/repo

RUN apk add --update bash

# build kcptun
ENV KCP_VER 20181002
ENV KCP_URL https://github.com/xtaci/kcptun/releases/download/v$KCP_VER/kcptun-linux-amd64-$KCP_VER.tar.gz

RUN apk update && \
    apk upgrade && \
    # get general dependency
    apk add --update bash curl openssl-dev && \
    # get kcpclient
    curl -sSL "$KCP_URL" | tar -xvzC /bin/ && \
    # clean general dependency
    apk del --purge curl openssl-dev


RUN apk add --update supervisor
RUN mkdir /service.conf.d
ADD sskcp-redir-x86.conf sskcp-server-x86.conf /service.conf.d/

CMD /bin/bash

